// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq_KHBDr5GvKIx_td2MNIY8K7paJtcm88',
    appId: '1:653784148768:web:9b6c6f28a9fa6de2f68545',
    messagingSenderId: '653784148768',
    projectId: 'diseno-de-aplicaciones-moviles',
    authDomain: 'diseno-de-aplicaciones-moviles.firebaseapp.com',
    storageBucket: 'diseno-de-aplicaciones-moviles.firebasestorage.app',
    measurementId: 'G-WF6EWPS7YF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuldcP2r1OTM1ucil8TQr2PLAPTJ74uH4',
    appId: '1:653784148768:android:841a3c972e437c2df68545',
    messagingSenderId: '653784148768',
    projectId: 'diseno-de-aplicaciones-moviles',
    storageBucket: 'diseno-de-aplicaciones-moviles.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAryT-zPSb_pm-4o03XakU-m1MJPAkJmM',
    appId: '1:653784148768:ios:17990293e619ee99f68545',
    messagingSenderId: '653784148768',
    projectId: 'diseno-de-aplicaciones-moviles',
    storageBucket: 'diseno-de-aplicaciones-moviles.firebasestorage.app',
    iosBundleId: 'com.example.ldswUtilizacionDeWidgets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAryT-zPSb_pm-4o03XakU-m1MJPAkJmM',
    appId: '1:653784148768:ios:17990293e619ee99f68545',
    messagingSenderId: '653784148768',
    projectId: 'diseno-de-aplicaciones-moviles',
    storageBucket: 'diseno-de-aplicaciones-moviles.firebasestorage.app',
    iosBundleId: 'com.example.ldswUtilizacionDeWidgets',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq_KHBDr5GvKIx_td2MNIY8K7paJtcm88',
    appId: '1:653784148768:web:22b093af6318852bf68545',
    messagingSenderId: '653784148768',
    projectId: 'diseno-de-aplicaciones-moviles',
    authDomain: 'diseno-de-aplicaciones-moviles.firebaseapp.com',
    storageBucket: 'diseno-de-aplicaciones-moviles.firebasestorage.app',
    measurementId: 'G-H8L5K01YB1',
  );
}
